### ISSUE TITLE
All actions are time.sleep functions

### ISSUE THREAD

**Issue by chapter09** [lzjzx1122/Pagurus#4]
Is it appropriate to use time.sleep functions to mimic the behaviors of real applications? How could you justify the amount of sleeping time? How to evaluate the memory consumption and utilization? For example, any memory waste? A forked Zygote container might stay in memory for a while before the next invocation hit it.

**Comment by lzjzx1122** [comment]
As mentioned in our paper, Pagurus intends to reduce the cold startups in serverless systems, it does not care whether function uses time.sleep(). If you are still concern about it, we also provide FunctionBench in this repo for you to evaluate the memory consumption and utilization. (https://github.com/lzjzx1122/Pagurus/tree/master/interaction_controller/actions)
